version: '2.3'
services:
    tensorflow:
        image: 'dbuades/tensorflow:2.0.0a0-gpu-py3'
        restart: unless-stopped
        runtime: nvidia
        container_name: flowy
        ports:
          - '2222:2222' #SSH for VS Code
          - '8888:8888' #JupyterNotebook
          - '6006:6006' #TensorBoard
        volumes:
          - tensorflow:/shared
volumes:
  tensorflow: